# Generated by Django 2.0.1 on 2019-01-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='first_name',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='second_name',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
    ]
