# Generated by Django 2.0.1 on 2019-01-11 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='memberships',
            new_name='services',
        ),
        migrations.AlterField(
            model_name='membership',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='services.UserProfile'),
        ),
    ]
