# Generated by Django 2.0.1 on 2019-01-18 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190118_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
