# Generated by Django 2.0.1 on 2019-01-12 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190111_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='api_url',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
