# Generated by Django 2.0.1 on 2019-01-07 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20190106_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='code',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='service',
            name='style',
        ),
        migrations.AddField(
            model_name='service',
            name='country',
            field=models.CharField(choices=[('CA', 'CA'), ('DE', 'DE'), ('FR', 'FR'), ('US', 'US')], default='US', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('airline', 'airline'), ('mart', 'mart'), ('spa', 'spa')], default='airline', max_length=100),
        ),
    ]
