# Generated by Django 2.0.1 on 2019-01-07 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_auto_20190107_0552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='owner',
        ),
        migrations.AlterField(
            model_name='service',
            name='country',
            field=models.CharField(choices=[('CA', 'CA'), ('DE', 'DE'), ('FR', 'FR'), ('UK', 'UK'), ('US', 'US')], default='US', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('airline', 'airline'), ('gym', 'gym'), ('mart', 'mart'), ('spa', 'spa'), ('taxi', 'taxi')], default='airline', max_length=100),
        ),
    ]
