# Generated by Django 2.0.1 on 2019-01-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='USD', max_length=100)),
                ('rate', models.CharField(default='1', max_length=100)),
                ('updated_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
