# Generated by Django 2.0.1 on 2019-01-21 05:49

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_myuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='000-0000', max_length=128, unique=True),
            preserve_default=False,
        ),
    ]
