# Generated by Django 2.0.1 on 2019-01-12 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20190112_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
