# Generated by Django 2.0.1 on 2019-01-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190107_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
