# Generated by Django 2.0.1 on 2019-01-21 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_auto_20190121_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(default='', max_length=100),
        ),
    ]
