# Generated by Django 2.0.1 on 2019-01-17 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_auto_20190116_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
