# Generated by Django 2.0.1 on 2019-01-23 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20190122_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='services',
            field=models.ManyToManyField(related_name='members', through='services.Membership', to='services.Service'),
        ),
    ]
