# Generated by Django 2.0.1 on 2019-01-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_auto_20190123_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='eth_public_key',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='eth_secret_key',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eth_public_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='eth_secret_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
