# Generated by Django 2.0.1 on 2019-01-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_membership_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=16),
        ),
    ]
