# Generated by Django 2.0.1 on 2019-01-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20190124_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='install_ts',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='membership',
            name='update_ts',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
