# Generated by Django 2.0.1 on 2019-01-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_redeemtransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currencyrate',
            old_name='updated_ts',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='install_ts',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='update_ts',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='redeemtransaction',
            old_name='updated_ts',
            new_name='created_at',
        ),
    ]
