# Generated by Django 2.0.1 on 2019-01-25 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_auto_20190125_0339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={},
        ),
    ]
