# Generated by Django 2.0.1 on 2019-01-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_auto_20190125_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
    ]
