# Generated by Django 2.0.1 on 2019-01-29 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_auto_20190129_1201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together={('profile', 'service', 'identifier')},
        ),
    ]
