# Generated by Django 2.0.1 on 2019-02-14 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_auto_20190213_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='redeemtransaction',
            name='tx_hash',
        ),
        migrations.RemoveField(
            model_name='transfertransaction',
            name='burn_tx_hash',
        ),
        migrations.RemoveField(
            model_name='transfertransaction',
            name='mint_tx_hash',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
    ]
